#pragma once
// The real one is generated by the build; only version strings read it.
#define GIT_REVISION "native-instrumented"
#define GIT_TAG      "native"
#define GIT_STATUS   "modified"
#define GIT_REPO     "local"
