/**
 * Writes `bladbaseExtras.ts`: for monsters 1–176, the fields Exile 3's own
 * monster table doesn't carry, taken from BoE 1997's `bladbase.exs` (Jeff
 * Vogel's export of these same monsters into Blades of Exile; GPL, from
 * `../boe-source-1997`). E3 keeps these in its code, not yet found.
 *
 *   npx vite-node tools/e3convert/genBladbaseExtras.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { legacyPlatform } from '../../src/fileio/legacy/loadLegacy';
import { LegacyReader, readItemData, readScenarioData } from '../../src/fileio/legacy/structs';

const src = fileURLToPath(new URL('../../../boe-source-1997/Macintosh Code Release 3/Scenario Editor/bladbase.exs', import.meta.url));
const data = new Uint8Array(readFileSync(src));
const r = new LegacyReader(data, legacyPlatform(data) === 'mac');
r.pos = 12; // the scenario header (loadLegacy.ts, HEADER_BYTES)
const { monsters } = readScenarioData(r);
const { items } = readItemData(r);
const rows = monsters.slice(1, 177).map((m) =>
  `  [${[m.breathType, m.radiate1, m.radiate2, m.defaultAttitude, m.summonType, m.defaultFacialPic, m.corpseItem, m.corpseItemChance].join(', ')}],`);
// Items by full name (the first of a name wins): the ability fields, which
// E3's own records either code differently or lack.
const seen = new Set<string>();
const itemRows: string[] = [];
for (const it of items) {
  if (!it.fullName || seen.has(it.fullName)) continue;
  seen.add(it.fullName);
  itemRows.push(`  [${JSON.stringify(it.fullName)}, [${[it.ability, it.abilityStrength, it.magicUseType, it.treasClass, it.type, it.itemProperties].join(', ')}]],`);
}
writeFileSync(fileURLToPath(new URL('./bladbaseExtras.ts', import.meta.url)), `/**
 * Generated by genBladbaseExtras.ts — do not edit. For E3 monsters 1–176
 * (index 0 is monster 1), the fields E3's table lacks, from BoE 1997's
 * bladbase.exs: [breathType, radiate1, radiate2, defaultAttitude,
 * summonType, defaultFacialPic, corpseItem, corpseItemChance].
 */
export const BLADBASE_EXTRAS: readonly (readonly number[])[] = [
${rows.join('\n')}
];

/**
 * BoE's items by full name: [ability, abilityStrength, magicUseType,
 * treasClass, type, itemProperties]. E3 items with a namesake here take these (see
 * tables.ts, readE3Items).
 */
export const BLADBASE_ITEMS: ReadonlyMap<string, readonly number[]> = new Map([
${itemRows.join('\n')}
]);
`);
console.log(`Wrote ${rows.length} monsters, ${itemRows.length} items.`);
